spring.application.name=fileApiServer
server.port=${PORT:8080}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# 토큰 발급용 내부 API KEY (실제 운영시에는 보안을 위해 외부에 노출되지 않도록 관리하세요)
internal.api.key=my-secure-internal-api-key
